"""
Author: David Pescariu, github.com/davidp-ro

Built with ❤️ and fully open-source.

--------------------------------------------------------------------------------------------------------
Main file is bot.py. This is a small module that splits the text if it dosen't fit in the embed message.
--------------------------------------------------------------------------------------------------------

License:
    
    MIT License ~~~ Copyright (c) 2020 David Pescariu

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

Disclaimer:
    Steam Stats Discord Bot is not associated/affiliated with Steam Inc. in any way shape or form.
    Steam Stats Discord Bot is not in any way shape or form endorsed by Steam Inc.

    Any copyright related issues shall be addresed either as an Issue on the github repository,
https://github.com/davidp-ro/Discord-Bots/issues, if it's not high-priority, or if neccesary on the
email: davidpescariu12 (at) gmail (dot) com
"""


class Trimmer():
    def game_stats(initial_text_left, initial_text_right):
        """
            This fucntion gets called when the stats don't fit in just two embeds and we need
        more, so this will generate 2 lists of strings, that will then be shown in embeds.

        Params:
            initial_text_left - String - the one generated by get_player_stats_to_show(bot.py)
            initial_text_right - String - the one generated by get_player_stats_to_show(bot.py)

        Returns:
            List, List, Int - text_left, text_right, return_code - 0 (succes) or 9 (failed)
        """
        text_left = []
        text_right = []

        word_counter, return_code = 0, 999

        try:
            text_left_to_append = ""
            text_right_to_append = ""

            for char in initial_text_left:
                if word_counter < 900:
                    text_left_to_append += char
                    word_counter += 1
                else:
                    text_left_to_append += '~'
                    word_counter = 0
            word_counter = 0
            for char in initial_text_right:
                if word_counter < 900:
                    text_right_to_append += char
                    word_counter += 1
                else:
                    text_right_to_append += '~'
                    word_counter = 0

            text_left.append(text_left_to_append.split('~'))
            text_right.append(text_right_to_append.split('~'))

            return_code = 0
            return text_left, text_right, return_code
        
        except:
            text_left.append('ERR_FAILED_TRIM')
            text_right.append('ERR_FAILED_TRIM')
            return_code = 9
            return text_left, text_left, return_code
